/**
 *
 *  ActivityLogs.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "ActivityLogs.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::qlattt;

const std::string ActivityLogs::Cols::_id = "\"id\"";
const std::string ActivityLogs::Cols::_admin_id = "\"admin_id\"";
const std::string ActivityLogs::Cols::_action = "\"action\"";
const std::string ActivityLogs::Cols::_entity = "\"entity\"";
const std::string ActivityLogs::Cols::_entity_id = "\"entity_id\"";
const std::string ActivityLogs::Cols::_detail = "\"detail\"";
const std::string ActivityLogs::Cols::_ip_address = "\"ip_address\"";
const std::string ActivityLogs::Cols::_created_at = "\"created_at\"";
const std::string ActivityLogs::primaryKeyName = "id";
const bool ActivityLogs::hasPrimaryKey = true;
const std::string ActivityLogs::tableName = "\"activity_logs\"";

const std::vector<typename ActivityLogs::MetaData> ActivityLogs::metaData_={
{"id","std::string","uuid",0,0,1,1},
{"admin_id","std::string","uuid",0,0,0,0},
{"action","std::string","USER-DEFINED",0,0,0,1},
{"entity","std::string","character varying",64,0,0,0},
{"entity_id","std::string","uuid",0,0,0,0},
{"detail","std::string","jsonb",0,0,0,0},
{"ip_address","std::string","inet",0,0,0,0},
{"created_at","::trantor::Date","timestamp with time zone",0,0,0,1}
};
const std::string &ActivityLogs::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
ActivityLogs::ActivityLogs(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["admin_id"].isNull())
        {
            adminId_=std::make_shared<std::string>(r["admin_id"].as<std::string>());
        }
        if(!r["action"].isNull())
        {
            action_=std::make_shared<std::string>(r["action"].as<std::string>());
        }
        if(!r["entity"].isNull())
        {
            entity_=std::make_shared<std::string>(r["entity"].as<std::string>());
        }
        if(!r["entity_id"].isNull())
        {
            entityId_=std::make_shared<std::string>(r["entity_id"].as<std::string>());
        }
        if(!r["detail"].isNull())
        {
            detail_=std::make_shared<std::string>(r["detail"].as<std::string>());
        }
        if(!r["ip_address"].isNull())
        {
            ipAddress_=std::make_shared<std::string>(r["ip_address"].as<std::string>());
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 8 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            adminId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            action_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            entity_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            entityId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            detail_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            ipAddress_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

ActivityLogs::ActivityLogs(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            adminId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            action_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            entity_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            entityId_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            detail_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            ipAddress_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

ActivityLogs::ActivityLogs(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("admin_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["admin_id"].isNull())
        {
            adminId_=std::make_shared<std::string>(pJson["admin_id"].asString());
        }
    }
    if(pJson.isMember("action"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["action"].isNull())
        {
            action_=std::make_shared<std::string>(pJson["action"].asString());
        }
    }
    if(pJson.isMember("entity"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["entity"].isNull())
        {
            entity_=std::make_shared<std::string>(pJson["entity"].asString());
        }
    }
    if(pJson.isMember("entity_id"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["entity_id"].isNull())
        {
            entityId_=std::make_shared<std::string>(pJson["entity_id"].asString());
        }
    }
    if(pJson.isMember("detail"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["detail"].isNull())
        {
            detail_=std::make_shared<std::string>(pJson["detail"].asString());
        }
    }
    if(pJson.isMember("ip_address"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["ip_address"].isNull())
        {
            ipAddress_=std::make_shared<std::string>(pJson["ip_address"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void ActivityLogs::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            adminId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            action_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            entity_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            entityId_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            detail_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            ipAddress_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void ActivityLogs::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("admin_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["admin_id"].isNull())
        {
            adminId_=std::make_shared<std::string>(pJson["admin_id"].asString());
        }
    }
    if(pJson.isMember("action"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["action"].isNull())
        {
            action_=std::make_shared<std::string>(pJson["action"].asString());
        }
    }
    if(pJson.isMember("entity"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["entity"].isNull())
        {
            entity_=std::make_shared<std::string>(pJson["entity"].asString());
        }
    }
    if(pJson.isMember("entity_id"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["entity_id"].isNull())
        {
            entityId_=std::make_shared<std::string>(pJson["entity_id"].asString());
        }
    }
    if(pJson.isMember("detail"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["detail"].isNull())
        {
            detail_=std::make_shared<std::string>(pJson["detail"].asString());
        }
    }
    if(pJson.isMember("ip_address"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["ip_address"].isNull())
        {
            ipAddress_=std::make_shared<std::string>(pJson["ip_address"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const std::string &ActivityLogs::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ActivityLogs::getId() const noexcept
{
    return id_;
}
void ActivityLogs::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void ActivityLogs::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename ActivityLogs::PrimaryKeyType & ActivityLogs::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &ActivityLogs::getValueOfAdminId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(adminId_)
        return *adminId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ActivityLogs::getAdminId() const noexcept
{
    return adminId_;
}
void ActivityLogs::setAdminId(const std::string &pAdminId) noexcept
{
    adminId_ = std::make_shared<std::string>(pAdminId);
    dirtyFlag_[1] = true;
}
void ActivityLogs::setAdminId(std::string &&pAdminId) noexcept
{
    adminId_ = std::make_shared<std::string>(std::move(pAdminId));
    dirtyFlag_[1] = true;
}
void ActivityLogs::setAdminIdToNull() noexcept
{
    adminId_.reset();
    dirtyFlag_[1] = true;
}

const std::string &ActivityLogs::getValueOfAction() const noexcept
{
    static const std::string defaultValue = std::string();
    if(action_)
        return *action_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ActivityLogs::getAction() const noexcept
{
    return action_;
}
void ActivityLogs::setAction(const std::string &pAction) noexcept
{
    action_ = std::make_shared<std::string>(pAction);
    dirtyFlag_[2] = true;
}
void ActivityLogs::setAction(std::string &&pAction) noexcept
{
    action_ = std::make_shared<std::string>(std::move(pAction));
    dirtyFlag_[2] = true;
}

const std::string &ActivityLogs::getValueOfEntity() const noexcept
{
    static const std::string defaultValue = std::string();
    if(entity_)
        return *entity_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ActivityLogs::getEntity() const noexcept
{
    return entity_;
}
void ActivityLogs::setEntity(const std::string &pEntity) noexcept
{
    entity_ = std::make_shared<std::string>(pEntity);
    dirtyFlag_[3] = true;
}
void ActivityLogs::setEntity(std::string &&pEntity) noexcept
{
    entity_ = std::make_shared<std::string>(std::move(pEntity));
    dirtyFlag_[3] = true;
}
void ActivityLogs::setEntityToNull() noexcept
{
    entity_.reset();
    dirtyFlag_[3] = true;
}

const std::string &ActivityLogs::getValueOfEntityId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(entityId_)
        return *entityId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ActivityLogs::getEntityId() const noexcept
{
    return entityId_;
}
void ActivityLogs::setEntityId(const std::string &pEntityId) noexcept
{
    entityId_ = std::make_shared<std::string>(pEntityId);
    dirtyFlag_[4] = true;
}
void ActivityLogs::setEntityId(std::string &&pEntityId) noexcept
{
    entityId_ = std::make_shared<std::string>(std::move(pEntityId));
    dirtyFlag_[4] = true;
}
void ActivityLogs::setEntityIdToNull() noexcept
{
    entityId_.reset();
    dirtyFlag_[4] = true;
}

const std::string &ActivityLogs::getValueOfDetail() const noexcept
{
    static const std::string defaultValue = std::string();
    if(detail_)
        return *detail_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ActivityLogs::getDetail() const noexcept
{
    return detail_;
}
void ActivityLogs::setDetail(const std::string &pDetail) noexcept
{
    detail_ = std::make_shared<std::string>(pDetail);
    dirtyFlag_[5] = true;
}
void ActivityLogs::setDetail(std::string &&pDetail) noexcept
{
    detail_ = std::make_shared<std::string>(std::move(pDetail));
    dirtyFlag_[5] = true;
}
void ActivityLogs::setDetailToNull() noexcept
{
    detail_.reset();
    dirtyFlag_[5] = true;
}

const std::string &ActivityLogs::getValueOfIpAddress() const noexcept
{
    static const std::string defaultValue = std::string();
    if(ipAddress_)
        return *ipAddress_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ActivityLogs::getIpAddress() const noexcept
{
    return ipAddress_;
}
void ActivityLogs::setIpAddress(const std::string &pIpAddress) noexcept
{
    ipAddress_ = std::make_shared<std::string>(pIpAddress);
    dirtyFlag_[6] = true;
}
void ActivityLogs::setIpAddress(std::string &&pIpAddress) noexcept
{
    ipAddress_ = std::make_shared<std::string>(std::move(pIpAddress));
    dirtyFlag_[6] = true;
}
void ActivityLogs::setIpAddressToNull() noexcept
{
    ipAddress_.reset();
    dirtyFlag_[6] = true;
}

const ::trantor::Date &ActivityLogs::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &ActivityLogs::getCreatedAt() const noexcept
{
    return createdAt_;
}
void ActivityLogs::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[7] = true;
}

void ActivityLogs::updateId(const uint64_t id)
{
}

const std::vector<std::string> &ActivityLogs::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "admin_id",
        "action",
        "entity",
        "entity_id",
        "detail",
        "ip_address",
        "created_at"
    };
    return inCols;
}

void ActivityLogs::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getAdminId())
        {
            binder << getValueOfAdminId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getAction())
        {
            binder << getValueOfAction();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getEntity())
        {
            binder << getValueOfEntity();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getEntityId())
        {
            binder << getValueOfEntityId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getDetail())
        {
            binder << getValueOfDetail();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getIpAddress())
        {
            binder << getValueOfIpAddress();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> ActivityLogs::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    return ret;
}

void ActivityLogs::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getAdminId())
        {
            binder << getValueOfAdminId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getAction())
        {
            binder << getValueOfAction();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getEntity())
        {
            binder << getValueOfEntity();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getEntityId())
        {
            binder << getValueOfEntityId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getDetail())
        {
            binder << getValueOfDetail();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getIpAddress())
        {
            binder << getValueOfIpAddress();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value ActivityLogs::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getAdminId())
    {
        ret["admin_id"]=getValueOfAdminId();
    }
    else
    {
        ret["admin_id"]=Json::Value();
    }
    if(getAction())
    {
        ret["action"]=getValueOfAction();
    }
    else
    {
        ret["action"]=Json::Value();
    }
    if(getEntity())
    {
        ret["entity"]=getValueOfEntity();
    }
    else
    {
        ret["entity"]=Json::Value();
    }
    if(getEntityId())
    {
        ret["entity_id"]=getValueOfEntityId();
    }
    else
    {
        ret["entity_id"]=Json::Value();
    }
    if(getDetail())
    {
        ret["detail"]=getValueOfDetail();
    }
    else
    {
        ret["detail"]=Json::Value();
    }
    if(getIpAddress())
    {
        ret["ip_address"]=getValueOfIpAddress();
    }
    else
    {
        ret["ip_address"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    return ret;
}

std::string ActivityLogs::toString() const
{
    return toJson().toStyledString();
}

Json::Value ActivityLogs::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 8)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getAdminId())
            {
                ret[pMasqueradingVector[1]]=getValueOfAdminId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getAction())
            {
                ret[pMasqueradingVector[2]]=getValueOfAction();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getEntity())
            {
                ret[pMasqueradingVector[3]]=getValueOfEntity();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getEntityId())
            {
                ret[pMasqueradingVector[4]]=getValueOfEntityId();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getDetail())
            {
                ret[pMasqueradingVector[5]]=getValueOfDetail();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getIpAddress())
            {
                ret[pMasqueradingVector[6]]=getValueOfIpAddress();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[7]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getAdminId())
    {
        ret["admin_id"]=getValueOfAdminId();
    }
    else
    {
        ret["admin_id"]=Json::Value();
    }
    if(getAction())
    {
        ret["action"]=getValueOfAction();
    }
    else
    {
        ret["action"]=Json::Value();
    }
    if(getEntity())
    {
        ret["entity"]=getValueOfEntity();
    }
    else
    {
        ret["entity"]=Json::Value();
    }
    if(getEntityId())
    {
        ret["entity_id"]=getValueOfEntityId();
    }
    else
    {
        ret["entity_id"]=Json::Value();
    }
    if(getDetail())
    {
        ret["detail"]=getValueOfDetail();
    }
    else
    {
        ret["detail"]=Json::Value();
    }
    if(getIpAddress())
    {
        ret["ip_address"]=getValueOfIpAddress();
    }
    else
    {
        ret["ip_address"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    return ret;
}

bool ActivityLogs::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("admin_id"))
    {
        if(!validJsonOfField(1, "admin_id", pJson["admin_id"], err, true))
            return false;
    }
    if(pJson.isMember("action"))
    {
        if(!validJsonOfField(2, "action", pJson["action"], err, true))
            return false;
    }
    else
    {
        err="The action column cannot be null";
        return false;
    }
    if(pJson.isMember("entity"))
    {
        if(!validJsonOfField(3, "entity", pJson["entity"], err, true))
            return false;
    }
    if(pJson.isMember("entity_id"))
    {
        if(!validJsonOfField(4, "entity_id", pJson["entity_id"], err, true))
            return false;
    }
    if(pJson.isMember("detail"))
    {
        if(!validJsonOfField(5, "detail", pJson["detail"], err, true))
            return false;
    }
    if(pJson.isMember("ip_address"))
    {
        if(!validJsonOfField(6, "ip_address", pJson["ip_address"], err, true))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(7, "created_at", pJson["created_at"], err, true))
            return false;
    }
    return true;
}
bool ActivityLogs::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool ActivityLogs::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("admin_id"))
    {
        if(!validJsonOfField(1, "admin_id", pJson["admin_id"], err, false))
            return false;
    }
    if(pJson.isMember("action"))
    {
        if(!validJsonOfField(2, "action", pJson["action"], err, false))
            return false;
    }
    if(pJson.isMember("entity"))
    {
        if(!validJsonOfField(3, "entity", pJson["entity"], err, false))
            return false;
    }
    if(pJson.isMember("entity_id"))
    {
        if(!validJsonOfField(4, "entity_id", pJson["entity_id"], err, false))
            return false;
    }
    if(pJson.isMember("detail"))
    {
        if(!validJsonOfField(5, "detail", pJson["detail"], err, false))
            return false;
    }
    if(pJson.isMember("ip_address"))
    {
        if(!validJsonOfField(6, "ip_address", pJson["ip_address"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(7, "created_at", pJson["created_at"], err, false))
            return false;
    }
    return true;
}
bool ActivityLogs::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool ActivityLogs::validJsonOfField(size_t index,
                                    const std::string &fieldName,
                                    const Json::Value &pJson,
                                    std::string &err,
                                    bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 64)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 64)";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
