#pragma once
#include <vector>
#include <string>
/**
 *
 *  ActivityLogs.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace qlattt
{

class ActivityLogs
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _admin_id;
        static const std::string _action;
        static const std::string _entity;
        static const std::string _entity_id;
        static const std::string _detail;
        static const std::string _ip_address;
        static const std::string _created_at;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = std::string;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit ActivityLogs(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit ActivityLogs(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    ActivityLogs(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    ActivityLogs() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const std::string &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const std::string &pId) noexcept;
    void setId(std::string &&pId) noexcept;

    /**  For column admin_id  */
    ///Get the value of the column admin_id, returns the default value if the column is null
    const std::string &getValueOfAdminId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getAdminId() const noexcept;
    ///Set the value of the column admin_id
    void setAdminId(const std::string &pAdminId) noexcept;
    void setAdminId(std::string &&pAdminId) noexcept;
    void setAdminIdToNull() noexcept;

    /**  For column action  */
    ///Get the value of the column action, returns the default value if the column is null
    const std::string &getValueOfAction() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getAction() const noexcept;
    ///Set the value of the column action
    void setAction(const std::string &pAction) noexcept;
    void setAction(std::string &&pAction) noexcept;

    /**  For column entity  */
    ///Get the value of the column entity, returns the default value if the column is null
    const std::string &getValueOfEntity() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getEntity() const noexcept;
    ///Set the value of the column entity
    void setEntity(const std::string &pEntity) noexcept;
    void setEntity(std::string &&pEntity) noexcept;
    void setEntityToNull() noexcept;

    /**  For column entity_id  */
    ///Get the value of the column entity_id, returns the default value if the column is null
    const std::string &getValueOfEntityId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getEntityId() const noexcept;
    ///Set the value of the column entity_id
    void setEntityId(const std::string &pEntityId) noexcept;
    void setEntityId(std::string &&pEntityId) noexcept;
    void setEntityIdToNull() noexcept;

    /**  For column detail  */
    ///Get the value of the column detail, returns the default value if the column is null
    const std::string &getValueOfDetail() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDetail() const noexcept;
    ///Set the value of the column detail
    void setDetail(const std::string &pDetail) noexcept;
    void setDetail(std::string &&pDetail) noexcept;
    void setDetailToNull() noexcept;

    /**  For column ip_address  */
    ///Get the value of the column ip_address, returns the default value if the column is null
    const std::string &getValueOfIpAddress() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getIpAddress() const noexcept;
    ///Set the value of the column ip_address
    void setIpAddress(const std::string &pIpAddress) noexcept;
    void setIpAddress(std::string &&pIpAddress) noexcept;
    void setIpAddressToNull() noexcept;

    /**  For column created_at  */
    ///Get the value of the column created_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfCreatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCreatedAt() const noexcept;
    ///Set the value of the column created_at
    void setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept;


    static size_t getColumnNumber() noexcept {  return 8;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<ActivityLogs>;
    friend drogon::orm::BaseBuilder<ActivityLogs, true, true>;
    friend drogon::orm::BaseBuilder<ActivityLogs, true, false>;
    friend drogon::orm::BaseBuilder<ActivityLogs, false, true>;
    friend drogon::orm::BaseBuilder<ActivityLogs, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<ActivityLogs>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<std::string> id_;
    std::shared_ptr<std::string> adminId_;
    std::shared_ptr<std::string> action_;
    std::shared_ptr<std::string> entity_;
    std::shared_ptr<std::string> entityId_;
    std::shared_ptr<std::string> detail_;
    std::shared_ptr<std::string> ipAddress_;
    std::shared_ptr<::trantor::Date> createdAt_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[8]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        sql += "id,";
        ++parametersCount;
        if(!dirtyFlag_[0])
        {
            needSelection=true;
        }
        if(dirtyFlag_[1])
        {
            sql += "admin_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "action,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "entity,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "entity_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "detail,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "ip_address,";
            ++parametersCount;
        }
        sql += "created_at,";
        ++parametersCount;
        if(!dirtyFlag_[7])
        {
            needSelection=true;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace qlattt
} // namespace drogon_model
