/**
#include <functional>
#include <memory>
#include <utility>
#include <vector>
 *
 *  RegistrationInterests.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "RegistrationInterests.h"
#include "Registrations.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::qlattt;

const std::string RegistrationInterests::Cols::_id = "\"id\"";
const std::string RegistrationInterests::Cols::_registration_id = "\"registration_id\"";
const std::string RegistrationInterests::Cols::_product_type = "\"product_type\"";
const std::string RegistrationInterests::primaryKeyName = "id";
const bool RegistrationInterests::hasPrimaryKey = true;
const std::string RegistrationInterests::tableName = "\"registration_interests\"";

const std::vector<typename RegistrationInterests::MetaData> RegistrationInterests::metaData_={
{"id","std::string","uuid",0,0,1,1},
{"registration_id","std::string","uuid",0,0,0,1},
{"product_type","std::string","USER-DEFINED",0,0,0,1}
};
const std::string &RegistrationInterests::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
RegistrationInterests::RegistrationInterests(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["registration_id"].isNull())
        {
            registrationId_=std::make_shared<std::string>(r["registration_id"].as<std::string>());
        }
        if(!r["product_type"].isNull())
        {
            productType_=std::make_shared<std::string>(r["product_type"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 3 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            registrationId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            productType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

RegistrationInterests::RegistrationInterests(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            registrationId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            productType_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
}

RegistrationInterests::RegistrationInterests(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("registration_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["registration_id"].isNull())
        {
            registrationId_=std::make_shared<std::string>(pJson["registration_id"].asString());
        }
    }
    if(pJson.isMember("product_type"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["product_type"].isNull())
        {
            productType_=std::make_shared<std::string>(pJson["product_type"].asString());
        }
    }
}

void RegistrationInterests::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            registrationId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            productType_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
}

void RegistrationInterests::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("registration_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["registration_id"].isNull())
        {
            registrationId_=std::make_shared<std::string>(pJson["registration_id"].asString());
        }
    }
    if(pJson.isMember("product_type"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["product_type"].isNull())
        {
            productType_=std::make_shared<std::string>(pJson["product_type"].asString());
        }
    }
}

const std::string &RegistrationInterests::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &RegistrationInterests::getId() const noexcept
{
    return id_;
}
void RegistrationInterests::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void RegistrationInterests::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename RegistrationInterests::PrimaryKeyType & RegistrationInterests::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &RegistrationInterests::getValueOfRegistrationId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(registrationId_)
        return *registrationId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &RegistrationInterests::getRegistrationId() const noexcept
{
    return registrationId_;
}
void RegistrationInterests::setRegistrationId(const std::string &pRegistrationId) noexcept
{
    registrationId_ = std::make_shared<std::string>(pRegistrationId);
    dirtyFlag_[1] = true;
}
void RegistrationInterests::setRegistrationId(std::string &&pRegistrationId) noexcept
{
    registrationId_ = std::make_shared<std::string>(std::move(pRegistrationId));
    dirtyFlag_[1] = true;
}

const std::string &RegistrationInterests::getValueOfProductType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(productType_)
        return *productType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &RegistrationInterests::getProductType() const noexcept
{
    return productType_;
}
void RegistrationInterests::setProductType(const std::string &pProductType) noexcept
{
    productType_ = std::make_shared<std::string>(pProductType);
    dirtyFlag_[2] = true;
}
void RegistrationInterests::setProductType(std::string &&pProductType) noexcept
{
    productType_ = std::make_shared<std::string>(std::move(pProductType));
    dirtyFlag_[2] = true;
}

void RegistrationInterests::updateId(const uint64_t id)
{
}

const std::vector<std::string> &RegistrationInterests::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "registration_id",
        "product_type"
    };
    return inCols;
}

void RegistrationInterests::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getRegistrationId())
        {
            binder << getValueOfRegistrationId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getProductType())
        {
            binder << getValueOfProductType();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> RegistrationInterests::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    return ret;
}

void RegistrationInterests::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getRegistrationId())
        {
            binder << getValueOfRegistrationId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getProductType())
        {
            binder << getValueOfProductType();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value RegistrationInterests::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getRegistrationId())
    {
        ret["registration_id"]=getValueOfRegistrationId();
    }
    else
    {
        ret["registration_id"]=Json::Value();
    }
    if(getProductType())
    {
        ret["product_type"]=getValueOfProductType();
    }
    else
    {
        ret["product_type"]=Json::Value();
    }
    return ret;
}

std::string RegistrationInterests::toString() const
{
    return toJson().toStyledString();
}

Json::Value RegistrationInterests::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 3)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getRegistrationId())
            {
                ret[pMasqueradingVector[1]]=getValueOfRegistrationId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getProductType())
            {
                ret[pMasqueradingVector[2]]=getValueOfProductType();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getRegistrationId())
    {
        ret["registration_id"]=getValueOfRegistrationId();
    }
    else
    {
        ret["registration_id"]=Json::Value();
    }
    if(getProductType())
    {
        ret["product_type"]=getValueOfProductType();
    }
    else
    {
        ret["product_type"]=Json::Value();
    }
    return ret;
}

bool RegistrationInterests::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("registration_id"))
    {
        if(!validJsonOfField(1, "registration_id", pJson["registration_id"], err, true))
            return false;
    }
    else
    {
        err="The registration_id column cannot be null";
        return false;
    }
    if(pJson.isMember("product_type"))
    {
        if(!validJsonOfField(2, "product_type", pJson["product_type"], err, true))
            return false;
    }
    else
    {
        err="The product_type column cannot be null";
        return false;
    }
    return true;
}
bool RegistrationInterests::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                               const std::vector<std::string> &pMasqueradingVector,
                                                               std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool RegistrationInterests::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("registration_id"))
    {
        if(!validJsonOfField(1, "registration_id", pJson["registration_id"], err, false))
            return false;
    }
    if(pJson.isMember("product_type"))
    {
        if(!validJsonOfField(2, "product_type", pJson["product_type"], err, false))
            return false;
    }
    return true;
}
bool RegistrationInterests::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                             const std::vector<std::string> &pMasqueradingVector,
                                                             std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool RegistrationInterests::validJsonOfField(size_t index,
                                             const std::string &fieldName,
                                             const Json::Value &pJson,
                                             std::string &err,
                                             bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
Registrations RegistrationInterests::getRegistration(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from registrations where id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *registrationId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Registrations(r[0]);
}

void RegistrationInterests::getRegistration(const DbClientPtr &clientPtr,
                                            const std::function<void(Registrations)> &rcb,
                                            const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from registrations where id = $1";
    *clientPtr << sql
               << *registrationId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Registrations(r[0]));
                    }
               }
               >> ecb;
}
