/**
#include <memory>
#include <utility>
#include <vector>
 *
 *  SiteSettings.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "SiteSettings.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::qlattt;

const std::string SiteSettings::Cols::_id = "\"id\"";
const std::string SiteSettings::Cols::_hotline = "\"hotline\"";
const std::string SiteSettings::Cols::_email = "\"email\"";
const std::string SiteSettings::Cols::_address = "\"address\"";
const std::string SiteSettings::Cols::_zalo_link = "\"zalo_link\"";
const std::string SiteSettings::Cols::_facebook_link = "\"facebook_link\"";
const std::string SiteSettings::Cols::_logo_url = "\"logo_url\"";
const std::string SiteSettings::Cols::_tagline = "\"tagline\"";
const std::string SiteSettings::Cols::_updated_by = "\"updated_by\"";
const std::string SiteSettings::Cols::_updated_at = "\"updated_at\"";
const std::string SiteSettings::primaryKeyName = "id";
const bool SiteSettings::hasPrimaryKey = true;
const std::string SiteSettings::tableName = "\"site_settings\"";

const std::vector<typename SiteSettings::MetaData> SiteSettings::metaData_={
{"id","std::string","uuid",0,0,1,1},
{"hotline","std::string","character varying",20,0,0,0},
{"email","std::string","character varying",128,0,0,0},
{"address","std::string","text",0,0,0,0},
{"zalo_link","std::string","text",0,0,0,0},
{"facebook_link","std::string","text",0,0,0,0},
{"logo_url","std::string","text",0,0,0,0},
{"tagline","std::string","text",0,0,0,0},
{"updated_by","std::string","uuid",0,0,0,0},
{"updated_at","::trantor::Date","timestamp with time zone",0,0,0,1}
};
const std::string &SiteSettings::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
SiteSettings::SiteSettings(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["hotline"].isNull())
        {
            hotline_=std::make_shared<std::string>(r["hotline"].as<std::string>());
        }
        if(!r["email"].isNull())
        {
            email_=std::make_shared<std::string>(r["email"].as<std::string>());
        }
        if(!r["address"].isNull())
        {
            address_=std::make_shared<std::string>(r["address"].as<std::string>());
        }
        if(!r["zalo_link"].isNull())
        {
            zaloLink_=std::make_shared<std::string>(r["zalo_link"].as<std::string>());
        }
        if(!r["facebook_link"].isNull())
        {
            facebookLink_=std::make_shared<std::string>(r["facebook_link"].as<std::string>());
        }
        if(!r["logo_url"].isNull())
        {
            logoUrl_=std::make_shared<std::string>(r["logo_url"].as<std::string>());
        }
        if(!r["tagline"].isNull())
        {
            tagline_=std::make_shared<std::string>(r["tagline"].as<std::string>());
        }
        if(!r["updated_by"].isNull())
        {
            updatedBy_=std::make_shared<std::string>(r["updated_by"].as<std::string>());
        }
        if(!r["updated_at"].isNull())
        {
            auto timeStr = r["updated_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 10 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            hotline_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            email_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            address_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            zaloLink_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            facebookLink_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            logoUrl_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            tagline_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            updatedBy_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

SiteSettings::SiteSettings(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 10)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            hotline_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            email_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            address_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            zaloLink_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            facebookLink_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            logoUrl_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            tagline_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            updatedBy_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[9]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

SiteSettings::SiteSettings(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("hotline"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["hotline"].isNull())
        {
            hotline_=std::make_shared<std::string>(pJson["hotline"].asString());
        }
    }
    if(pJson.isMember("email"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["email"].isNull())
        {
            email_=std::make_shared<std::string>(pJson["email"].asString());
        }
    }
    if(pJson.isMember("address"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["address"].isNull())
        {
            address_=std::make_shared<std::string>(pJson["address"].asString());
        }
    }
    if(pJson.isMember("zalo_link"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["zalo_link"].isNull())
        {
            zaloLink_=std::make_shared<std::string>(pJson["zalo_link"].asString());
        }
    }
    if(pJson.isMember("facebook_link"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["facebook_link"].isNull())
        {
            facebookLink_=std::make_shared<std::string>(pJson["facebook_link"].asString());
        }
    }
    if(pJson.isMember("logo_url"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["logo_url"].isNull())
        {
            logoUrl_=std::make_shared<std::string>(pJson["logo_url"].asString());
        }
    }
    if(pJson.isMember("tagline"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["tagline"].isNull())
        {
            tagline_=std::make_shared<std::string>(pJson["tagline"].asString());
        }
    }
    if(pJson.isMember("updated_by"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["updated_by"].isNull())
        {
            updatedBy_=std::make_shared<std::string>(pJson["updated_by"].asString());
        }
    }
    if(pJson.isMember("updated_at"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["updated_at"].isNull())
        {
            auto timeStr = pJson["updated_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void SiteSettings::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 10)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            hotline_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            email_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            address_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            zaloLink_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            facebookLink_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            logoUrl_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            tagline_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            updatedBy_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[9]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void SiteSettings::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("hotline"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["hotline"].isNull())
        {
            hotline_=std::make_shared<std::string>(pJson["hotline"].asString());
        }
    }
    if(pJson.isMember("email"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["email"].isNull())
        {
            email_=std::make_shared<std::string>(pJson["email"].asString());
        }
    }
    if(pJson.isMember("address"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["address"].isNull())
        {
            address_=std::make_shared<std::string>(pJson["address"].asString());
        }
    }
    if(pJson.isMember("zalo_link"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["zalo_link"].isNull())
        {
            zaloLink_=std::make_shared<std::string>(pJson["zalo_link"].asString());
        }
    }
    if(pJson.isMember("facebook_link"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["facebook_link"].isNull())
        {
            facebookLink_=std::make_shared<std::string>(pJson["facebook_link"].asString());
        }
    }
    if(pJson.isMember("logo_url"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["logo_url"].isNull())
        {
            logoUrl_=std::make_shared<std::string>(pJson["logo_url"].asString());
        }
    }
    if(pJson.isMember("tagline"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["tagline"].isNull())
        {
            tagline_=std::make_shared<std::string>(pJson["tagline"].asString());
        }
    }
    if(pJson.isMember("updated_by"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["updated_by"].isNull())
        {
            updatedBy_=std::make_shared<std::string>(pJson["updated_by"].asString());
        }
    }
    if(pJson.isMember("updated_at"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["updated_at"].isNull())
        {
            auto timeStr = pJson["updated_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const std::string &SiteSettings::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SiteSettings::getId() const noexcept
{
    return id_;
}
void SiteSettings::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void SiteSettings::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename SiteSettings::PrimaryKeyType & SiteSettings::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &SiteSettings::getValueOfHotline() const noexcept
{
    static const std::string defaultValue = std::string();
    if(hotline_)
        return *hotline_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SiteSettings::getHotline() const noexcept
{
    return hotline_;
}
void SiteSettings::setHotline(const std::string &pHotline) noexcept
{
    hotline_ = std::make_shared<std::string>(pHotline);
    dirtyFlag_[1] = true;
}
void SiteSettings::setHotline(std::string &&pHotline) noexcept
{
    hotline_ = std::make_shared<std::string>(std::move(pHotline));
    dirtyFlag_[1] = true;
}
void SiteSettings::setHotlineToNull() noexcept
{
    hotline_.reset();
    dirtyFlag_[1] = true;
}

const std::string &SiteSettings::getValueOfEmail() const noexcept
{
    static const std::string defaultValue = std::string();
    if(email_)
        return *email_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SiteSettings::getEmail() const noexcept
{
    return email_;
}
void SiteSettings::setEmail(const std::string &pEmail) noexcept
{
    email_ = std::make_shared<std::string>(pEmail);
    dirtyFlag_[2] = true;
}
void SiteSettings::setEmail(std::string &&pEmail) noexcept
{
    email_ = std::make_shared<std::string>(std::move(pEmail));
    dirtyFlag_[2] = true;
}
void SiteSettings::setEmailToNull() noexcept
{
    email_.reset();
    dirtyFlag_[2] = true;
}

const std::string &SiteSettings::getValueOfAddress() const noexcept
{
    static const std::string defaultValue = std::string();
    if(address_)
        return *address_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SiteSettings::getAddress() const noexcept
{
    return address_;
}
void SiteSettings::setAddress(const std::string &pAddress) noexcept
{
    address_ = std::make_shared<std::string>(pAddress);
    dirtyFlag_[3] = true;
}
void SiteSettings::setAddress(std::string &&pAddress) noexcept
{
    address_ = std::make_shared<std::string>(std::move(pAddress));
    dirtyFlag_[3] = true;
}
void SiteSettings::setAddressToNull() noexcept
{
    address_.reset();
    dirtyFlag_[3] = true;
}

const std::string &SiteSettings::getValueOfZaloLink() const noexcept
{
    static const std::string defaultValue = std::string();
    if(zaloLink_)
        return *zaloLink_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SiteSettings::getZaloLink() const noexcept
{
    return zaloLink_;
}
void SiteSettings::setZaloLink(const std::string &pZaloLink) noexcept
{
    zaloLink_ = std::make_shared<std::string>(pZaloLink);
    dirtyFlag_[4] = true;
}
void SiteSettings::setZaloLink(std::string &&pZaloLink) noexcept
{
    zaloLink_ = std::make_shared<std::string>(std::move(pZaloLink));
    dirtyFlag_[4] = true;
}
void SiteSettings::setZaloLinkToNull() noexcept
{
    zaloLink_.reset();
    dirtyFlag_[4] = true;
}

const std::string &SiteSettings::getValueOfFacebookLink() const noexcept
{
    static const std::string defaultValue = std::string();
    if(facebookLink_)
        return *facebookLink_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SiteSettings::getFacebookLink() const noexcept
{
    return facebookLink_;
}
void SiteSettings::setFacebookLink(const std::string &pFacebookLink) noexcept
{
    facebookLink_ = std::make_shared<std::string>(pFacebookLink);
    dirtyFlag_[5] = true;
}
void SiteSettings::setFacebookLink(std::string &&pFacebookLink) noexcept
{
    facebookLink_ = std::make_shared<std::string>(std::move(pFacebookLink));
    dirtyFlag_[5] = true;
}
void SiteSettings::setFacebookLinkToNull() noexcept
{
    facebookLink_.reset();
    dirtyFlag_[5] = true;
}

const std::string &SiteSettings::getValueOfLogoUrl() const noexcept
{
    static const std::string defaultValue = std::string();
    if(logoUrl_)
        return *logoUrl_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SiteSettings::getLogoUrl() const noexcept
{
    return logoUrl_;
}
void SiteSettings::setLogoUrl(const std::string &pLogoUrl) noexcept
{
    logoUrl_ = std::make_shared<std::string>(pLogoUrl);
    dirtyFlag_[6] = true;
}
void SiteSettings::setLogoUrl(std::string &&pLogoUrl) noexcept
{
    logoUrl_ = std::make_shared<std::string>(std::move(pLogoUrl));
    dirtyFlag_[6] = true;
}
void SiteSettings::setLogoUrlToNull() noexcept
{
    logoUrl_.reset();
    dirtyFlag_[6] = true;
}

const std::string &SiteSettings::getValueOfTagline() const noexcept
{
    static const std::string defaultValue = std::string();
    if(tagline_)
        return *tagline_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SiteSettings::getTagline() const noexcept
{
    return tagline_;
}
void SiteSettings::setTagline(const std::string &pTagline) noexcept
{
    tagline_ = std::make_shared<std::string>(pTagline);
    dirtyFlag_[7] = true;
}
void SiteSettings::setTagline(std::string &&pTagline) noexcept
{
    tagline_ = std::make_shared<std::string>(std::move(pTagline));
    dirtyFlag_[7] = true;
}
void SiteSettings::setTaglineToNull() noexcept
{
    tagline_.reset();
    dirtyFlag_[7] = true;
}

const std::string &SiteSettings::getValueOfUpdatedBy() const noexcept
{
    static const std::string defaultValue = std::string();
    if(updatedBy_)
        return *updatedBy_;
    return defaultValue;
}
const std::shared_ptr<std::string> &SiteSettings::getUpdatedBy() const noexcept
{
    return updatedBy_;
}
void SiteSettings::setUpdatedBy(const std::string &pUpdatedBy) noexcept
{
    updatedBy_ = std::make_shared<std::string>(pUpdatedBy);
    dirtyFlag_[8] = true;
}
void SiteSettings::setUpdatedBy(std::string &&pUpdatedBy) noexcept
{
    updatedBy_ = std::make_shared<std::string>(std::move(pUpdatedBy));
    dirtyFlag_[8] = true;
}
void SiteSettings::setUpdatedByToNull() noexcept
{
    updatedBy_.reset();
    dirtyFlag_[8] = true;
}

const ::trantor::Date &SiteSettings::getValueOfUpdatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(updatedAt_)
        return *updatedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &SiteSettings::getUpdatedAt() const noexcept
{
    return updatedAt_;
}
void SiteSettings::setUpdatedAt(const ::trantor::Date &pUpdatedAt) noexcept
{
    updatedAt_ = std::make_shared<::trantor::Date>(pUpdatedAt);
    dirtyFlag_[9] = true;
}

void SiteSettings::updateId(const uint64_t id)
{
}

const std::vector<std::string> &SiteSettings::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "hotline",
        "email",
        "address",
        "zalo_link",
        "facebook_link",
        "logo_url",
        "tagline",
        "updated_by",
        "updated_at"
    };
    return inCols;
}

void SiteSettings::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getHotline())
        {
            binder << getValueOfHotline();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getEmail())
        {
            binder << getValueOfEmail();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getAddress())
        {
            binder << getValueOfAddress();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getZaloLink())
        {
            binder << getValueOfZaloLink();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getFacebookLink())
        {
            binder << getValueOfFacebookLink();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getLogoUrl())
        {
            binder << getValueOfLogoUrl();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getTagline())
        {
            binder << getValueOfTagline();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getUpdatedBy())
        {
            binder << getValueOfUpdatedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getUpdatedAt())
        {
            binder << getValueOfUpdatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> SiteSettings::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    return ret;
}

void SiteSettings::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getHotline())
        {
            binder << getValueOfHotline();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getEmail())
        {
            binder << getValueOfEmail();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getAddress())
        {
            binder << getValueOfAddress();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getZaloLink())
        {
            binder << getValueOfZaloLink();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getFacebookLink())
        {
            binder << getValueOfFacebookLink();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getLogoUrl())
        {
            binder << getValueOfLogoUrl();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getTagline())
        {
            binder << getValueOfTagline();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getUpdatedBy())
        {
            binder << getValueOfUpdatedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getUpdatedAt())
        {
            binder << getValueOfUpdatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value SiteSettings::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getHotline())
    {
        ret["hotline"]=getValueOfHotline();
    }
    else
    {
        ret["hotline"]=Json::Value();
    }
    if(getEmail())
    {
        ret["email"]=getValueOfEmail();
    }
    else
    {
        ret["email"]=Json::Value();
    }
    if(getAddress())
    {
        ret["address"]=getValueOfAddress();
    }
    else
    {
        ret["address"]=Json::Value();
    }
    if(getZaloLink())
    {
        ret["zalo_link"]=getValueOfZaloLink();
    }
    else
    {
        ret["zalo_link"]=Json::Value();
    }
    if(getFacebookLink())
    {
        ret["facebook_link"]=getValueOfFacebookLink();
    }
    else
    {
        ret["facebook_link"]=Json::Value();
    }
    if(getLogoUrl())
    {
        ret["logo_url"]=getValueOfLogoUrl();
    }
    else
    {
        ret["logo_url"]=Json::Value();
    }
    if(getTagline())
    {
        ret["tagline"]=getValueOfTagline();
    }
    else
    {
        ret["tagline"]=Json::Value();
    }
    if(getUpdatedBy())
    {
        ret["updated_by"]=getValueOfUpdatedBy();
    }
    else
    {
        ret["updated_by"]=Json::Value();
    }
    if(getUpdatedAt())
    {
        ret["updated_at"]=getUpdatedAt()->toDbStringLocal();
    }
    else
    {
        ret["updated_at"]=Json::Value();
    }
    return ret;
}

std::string SiteSettings::toString() const
{
    return toJson().toStyledString();
}

Json::Value SiteSettings::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 10)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getHotline())
            {
                ret[pMasqueradingVector[1]]=getValueOfHotline();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getEmail())
            {
                ret[pMasqueradingVector[2]]=getValueOfEmail();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getAddress())
            {
                ret[pMasqueradingVector[3]]=getValueOfAddress();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getZaloLink())
            {
                ret[pMasqueradingVector[4]]=getValueOfZaloLink();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getFacebookLink())
            {
                ret[pMasqueradingVector[5]]=getValueOfFacebookLink();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getLogoUrl())
            {
                ret[pMasqueradingVector[6]]=getValueOfLogoUrl();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getTagline())
            {
                ret[pMasqueradingVector[7]]=getValueOfTagline();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getUpdatedBy())
            {
                ret[pMasqueradingVector[8]]=getValueOfUpdatedBy();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getUpdatedAt())
            {
                ret[pMasqueradingVector[9]]=getUpdatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getHotline())
    {
        ret["hotline"]=getValueOfHotline();
    }
    else
    {
        ret["hotline"]=Json::Value();
    }
    if(getEmail())
    {
        ret["email"]=getValueOfEmail();
    }
    else
    {
        ret["email"]=Json::Value();
    }
    if(getAddress())
    {
        ret["address"]=getValueOfAddress();
    }
    else
    {
        ret["address"]=Json::Value();
    }
    if(getZaloLink())
    {
        ret["zalo_link"]=getValueOfZaloLink();
    }
    else
    {
        ret["zalo_link"]=Json::Value();
    }
    if(getFacebookLink())
    {
        ret["facebook_link"]=getValueOfFacebookLink();
    }
    else
    {
        ret["facebook_link"]=Json::Value();
    }
    if(getLogoUrl())
    {
        ret["logo_url"]=getValueOfLogoUrl();
    }
    else
    {
        ret["logo_url"]=Json::Value();
    }
    if(getTagline())
    {
        ret["tagline"]=getValueOfTagline();
    }
    else
    {
        ret["tagline"]=Json::Value();
    }
    if(getUpdatedBy())
    {
        ret["updated_by"]=getValueOfUpdatedBy();
    }
    else
    {
        ret["updated_by"]=Json::Value();
    }
    if(getUpdatedAt())
    {
        ret["updated_at"]=getUpdatedAt()->toDbStringLocal();
    }
    else
    {
        ret["updated_at"]=Json::Value();
    }
    return ret;
}

bool SiteSettings::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("hotline"))
    {
        if(!validJsonOfField(1, "hotline", pJson["hotline"], err, true))
            return false;
    }
    if(pJson.isMember("email"))
    {
        if(!validJsonOfField(2, "email", pJson["email"], err, true))
            return false;
    }
    if(pJson.isMember("address"))
    {
        if(!validJsonOfField(3, "address", pJson["address"], err, true))
            return false;
    }
    if(pJson.isMember("zalo_link"))
    {
        if(!validJsonOfField(4, "zalo_link", pJson["zalo_link"], err, true))
            return false;
    }
    if(pJson.isMember("facebook_link"))
    {
        if(!validJsonOfField(5, "facebook_link", pJson["facebook_link"], err, true))
            return false;
    }
    if(pJson.isMember("logo_url"))
    {
        if(!validJsonOfField(6, "logo_url", pJson["logo_url"], err, true))
            return false;
    }
    if(pJson.isMember("tagline"))
    {
        if(!validJsonOfField(7, "tagline", pJson["tagline"], err, true))
            return false;
    }
    if(pJson.isMember("updated_by"))
    {
        if(!validJsonOfField(8, "updated_by", pJson["updated_by"], err, true))
            return false;
    }
    if(pJson.isMember("updated_at"))
    {
        if(!validJsonOfField(9, "updated_at", pJson["updated_at"], err, true))
            return false;
    }
    return true;
}
bool SiteSettings::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 10)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool SiteSettings::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("hotline"))
    {
        if(!validJsonOfField(1, "hotline", pJson["hotline"], err, false))
            return false;
    }
    if(pJson.isMember("email"))
    {
        if(!validJsonOfField(2, "email", pJson["email"], err, false))
            return false;
    }
    if(pJson.isMember("address"))
    {
        if(!validJsonOfField(3, "address", pJson["address"], err, false))
            return false;
    }
    if(pJson.isMember("zalo_link"))
    {
        if(!validJsonOfField(4, "zalo_link", pJson["zalo_link"], err, false))
            return false;
    }
    if(pJson.isMember("facebook_link"))
    {
        if(!validJsonOfField(5, "facebook_link", pJson["facebook_link"], err, false))
            return false;
    }
    if(pJson.isMember("logo_url"))
    {
        if(!validJsonOfField(6, "logo_url", pJson["logo_url"], err, false))
            return false;
    }
    if(pJson.isMember("tagline"))
    {
        if(!validJsonOfField(7, "tagline", pJson["tagline"], err, false))
            return false;
    }
    if(pJson.isMember("updated_by"))
    {
        if(!validJsonOfField(8, "updated_by", pJson["updated_by"], err, false))
            return false;
    }
    if(pJson.isMember("updated_at"))
    {
        if(!validJsonOfField(9, "updated_at", pJson["updated_at"], err, false))
            return false;
    }
    return true;
}
bool SiteSettings::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 10)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool SiteSettings::validJsonOfField(size_t index,
                                    const std::string &fieldName,
                                    const Json::Value &pJson,
                                    std::string &err,
                                    bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 20)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 20)";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 128)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 128)";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
